### ISSUE TITLE
Data source 'Blah.Blah' cannot be found in the test configuration settings

### ISSUE THREAD

**Issue by somewhatabstract** [Thwaitesy/MSTestHacks#12]
I have an App.config (it already contains some configuration information, but I've tried it empty also). Using VS2015 RC and latest Nuget package. I also tried the examples from your repo, but attempting to open one of the source files for the tests crashed VC2015 RC.

Cannot work out what is happening.

**Comment by somewhatabstract** [comment]
Okay, got the example tests to run and they pass. Cannot work out what is different in my tests that it doesn't work.

**Comment by somewhatabstract** [comment]
Since it clearly works for the test scenarios, I'll close this issue. You don't need to be debugging my mistakes. If I find something concrete, I will return. :smile:

**Comment by somewhatabstract** [comment]
OK, turns out I hadn't tried an empty app.config. I deleted all the sections out of my configuration and it started passing. I think that this may be creating an invalid app.config by assuming the config is empty. Mine has custom sections defined via `configSections`, `startup`, and `runtime` in there to support some of the test scenarios.

**Comment by somewhatabstract** [comment]
As an experiment I ran without any custom config sections in the app.config (i.e. config sections based on types defined in our codebase), and it worked. So, perhaps it has something to do with how it loads the config and not being able to resolve the custom sections?

**Comment by somewhatabstract** [comment]
Based off [this answer StackOverflow](http://stackoverflow.com/a/1682968/23234), I think it's trying to resolve the custom type from DLLs in the folder of the test runner, not the DLL under test and so it is failing to load the app.config.

I don't know how to work around this, other than to manipulate the app.config without the ConfigurationManager - perhaps via LINQ-to-XML instead?

**Comment by kiranjulapalli** [comment]
I am seeing the same issue. Installed with Nuget, I already have an app.config with a whole bunch of settings and it fails saying, "Data source <> cannot be found in the test configuration settings"

**Comment by kiranjulapalli** [comment]
I am seeing the same issue. Installed with Nuget, I already have an app.config with a whole bunch of settings and it fails saying, "Data source <> cannot be found in the test configuration settings"
