### ISSUE TITLE
How to specify method to test in  ExceptionAssert.Throws

### ISSUE THREAD

**Issue by MNF** [Thwaitesy/MSTestHacks#20]
Do you consider to enable github wiki?
I was trying to invoke method like the following
` ExceptionAssert.Throws<Exception>(MyMethod(myParameters), validatorForException: x => x.Message == "This is silly");`

but the correct way to call is 
```
ExceptionAssert.Throws<ApplicationException>(() =>
   MyMethod(myParameters) ,
    validatorForException: x => x.Message == expectedMessage);
```

It will be useful to highlight in your documentation.

**Comment by Thwaitesy** [comment]
I have enabled the wiki for you.

Cheers,
Sam
