### ISSUE TITLE
Is ExceptionAssert.Throws better than FluentAssertions.ShouldThrow ?

### ISSUE THREAD

**Issue by MNF** [Thwaitesy/MSTestHacks#22]
I was using ExceptionAssert.Throws and  even done some improvements(see pull request https://github.com/Thwaitesy/MSTestHacks/pull/21) . But recently I found that FluentAssertions(that we are using anyway)  have  very similar ShouldThrow
https://github.com/dennisdoomen/fluentassertions/wiki#exceptions with many variances,
E.g.
Action act = () => subject.Foo(null)); 
act.ShouldThrow<ArgumentNullException>().Where(e => e.Message.StartsWith("did"));

Could you advice is your ExceptionAssert has any advantages compare to FluentAssertions ShouldThrow    ?

**Comment by Thwaitesy** [comment]
Hi,

They look very very similar, I haven't used fluent assertions before but I would doubt there are any major advantages with MSTestHacks over them.
