### ISSUE TITLE
Data Source Example TrueOrFalse

### ISSUE THREAD

**Issue by MNF** [Thwaitesy/MSTestHacks#23]
I suggest to provide examples of DataSources, than can be used out of the box, e.g. the simple one
[DataSource("TestDataSourceExamples.TrueOrFalse")]

public IEnumerable<bool> TrueOrFalse
        {
            get
            {
                return new List< bool> { true, false};
            }
        }

**Comment by Thwaitesy** [comment]
Great idea!

Happy to accept changes to documentation etc. Just send in a PR.

**Comment by Thwaitesy** [comment]
I have also just enabled the wiki for you.
