### ISSUE TITLE
Question - Issue with Studio 2013

### ISSUE THREAD

**Issue by white-rr** [Thwaitesy/MSTestHacks#5]
I'm receiving the following error when I try and run under VS2013:
Message: Data source 'Namespace.Unters1.Stuff' cannot be found in the test configuration settings

I created a class directly from the source in your example, see below : 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using MSTestHacks;

namespace Namespace
{
  [TestClass]
  public class UnitTest1 : TestBase
  {
    private IEnumerable<int> Stuff
    {
      get
      {
        //This could do anything, get a dynamic list from anywhere....
        return new List<int> { 1, 2, 3 };
      }
    }

```
[TestMethod]
[DataSource("Namespace.UnitTest1.Stuff")]
public void TestMethod1()
{
  var number = this.TestContext.GetRuntimeDataSourceObject<int>();

  Assert.IsNotNull(number);
}
```

  }
}

When I attempt to run I get the error listed above.  Any suggestions?

**Comment by kiranjulapalli** [comment]
I have version 2.3.5.0 and am getting the issue that the data source cannot be found in test configuration settings. Am running visualstudio 2013
