### ISSUE TITLE
MSTest data driven Test do not create a new test for Rows from DataSource

### ISSUE THREAD

**Issue by mach22** [Thwaitesy/MSTestHacks#9]
Using NUnit with parametrized test if the parameters are different (I think based on ToString() of the paraters passed to the TestMethod) in the TestExplorer I can see N test as the number of the rows.
So that I can run each test as a single test. (while using MStest I need to run every time all the tests)
Is there any way for doing this?

**Comment by Thwaitesy** [comment]
I think what you are referring to is re-sharpers test explorer window? 

Microsoft Visual Studio's built in test explorer has no feature like you are discussing and no ability to extend it (to my knowledge).
